# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "CI-CD-Testing" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: List available Xcode versions
       # run: ls /Applications | grep Xcode

     # - name: Set up Xcode version
      #  run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

     # - name: Print working directory
      #  run: pwd

     # - name: List directory contents
      #  run: ls -al

      - name: Build list
        run: xcodebuild -list

      - name: Build app
        run: |
          xcodebuild -project StackProblem1.xcodeproj \
                     -scheme StackProblem1 \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15'
